techsales_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: gg
      port: 5432
      dbname: techsales_mx
      schema: analytics
      threads: 4


      